import type { Farm } from '@/types/farm';

export const mockFarms: Farm[] = [
  {
    id: 'uniswap-v3-eth-usdc',
    name: 'ETH-USDC',
    protocol: 'Uniswap V3',
    chain: 'ethereum',
    tokens: ['ETH', 'USDC'],
    tvl: 245000000,
    tvlChange24h: 2.5,
    baseAPY: 4.2,
    rewardAPY: 8.5,
    totalAPY: 12.7,
    riskScore: 25,
    poolType: 'concentrated',
    ilRisk: 'Medium',
    farmUrl: 'https://app.uniswap.org/pools',
    isStablecoin: false,
  },
  {
    id: 'aave-v3-usdc',
    name: 'USDC Lending',
    protocol: 'Aave V3',
    chain: 'ethereum',
    tokens: ['USDC'],
    tvl: 1200000000,
    tvlChange24h: 1.2,
    baseAPY: 5.8,
    rewardAPY: 2.1,
    totalAPY: 7.9,
    riskScore: 15,
    poolType: 'lending',
    ilRisk: 'None',
    farmUrl: 'https://app.aave.com',
    isStablecoin: true,
  },
  {
    id: 'curve-3pool',
    name: '3Pool',
    protocol: 'Curve',
    chain: 'ethereum',
    tokens: ['DAI', 'USDC', 'USDT'],
    tvl: 890000000,
    tvlChange24h: -0.8,
    baseAPY: 2.1,
    rewardAPY: 4.5,
    totalAPY: 6.6,
    riskScore: 20,
    poolType: 'stable',
    ilRisk: 'Low',
    farmUrl: 'https://curve.fi',
    isStablecoin: true,
  },
  {
    id: 'gmx-glp',
    name: 'GLP',
    protocol: 'GMX',
    chain: 'arbitrum',
    tokens: ['ETH', 'BTC', 'USDC', 'USDT'],
    tvl: 450000000,
    tvlChange24h: 3.2,
    baseAPY: 15.2,
    rewardAPY: 8.3,
    totalAPY: 23.5,
    riskScore: 45,
    poolType: 'index',
    ilRisk: 'Medium',
    farmUrl: 'https://app.gmx.io',
    isStablecoin: false,
  },
  {
    id: 'aerodrome-eth-usdc',
    name: 'ETH-USDC',
    protocol: 'Aerodrome',
    chain: 'base',
    tokens: ['ETH', 'USDC'],
    tvl: 125000000,
    tvlChange24h: 5.8,
    baseAPY: 8.5,
    rewardAPY: 18.2,
    totalAPY: 26.7,
    riskScore: 35,
    poolType: 'amm',
    ilRisk: 'Medium',
    farmUrl: 'https://aerodrome.finance',
    isStablecoin: false,
  },
  {
    id: 'pancake-cake-bnb',
    name: 'CAKE-BNB',
    protocol: 'PancakeSwap',
    chain: 'bnb',
    tokens: ['CAKE', 'BNB'],
    tvl: 78000000,
    tvlChange24h: -1.5,
    baseAPY: 12.3,
    rewardAPY: 25.8,
    totalAPY: 38.1,
    riskScore: 55,
    poolType: 'amm',
    ilRisk: 'High',
    farmUrl: 'https://pancakeswap.finance',
    isStablecoin: false,
  },
  {
    id: 'raydium-sol-usdc',
    name: 'SOL-USDC',
    protocol: 'Raydium',
    chain: 'solana',
    tokens: ['SOL', 'USDC'],
    tvl: 95000000,
    tvlChange24h: 4.2,
    baseAPY: 6.8,
    rewardAPY: 15.4,
    totalAPY: 22.2,
    riskScore: 40,
    poolType: 'concentrated',
    ilRisk: 'Medium',
    farmUrl: 'https://raydium.io',
    isStablecoin: false,
  },
  {
    id: 'compound-eth',
    name: 'ETH Lending',
    protocol: 'Compound',
    chain: 'ethereum',
    tokens: ['ETH'],
    tvl: 560000000,
    tvlChange24h: 0.9,
    baseAPY: 3.2,
    rewardAPY: 1.8,
    totalAPY: 5.0,
    riskScore: 18,
    poolType: 'lending',
    ilRisk: 'None',
    farmUrl: 'https://compound.finance',
    isStablecoin: false,
  },
  {
    id: 'convex-steth',
    name: 'stETH-ETH',
    protocol: 'Convex',
    chain: 'ethereum',
    tokens: ['stETH', 'ETH'],
    tvl: 320000000,
    tvlChange24h: 1.1,
    baseAPY: 4.5,
    rewardAPY: 3.2,
    totalAPY: 7.7,
    riskScore: 22,
    poolType: 'stable',
    ilRisk: 'Low',
    farmUrl: 'https://convexfinance.com',
    isStablecoin: false,
  },
  {
    id: 'lido-steth',
    name: 'stETH Staking',
    protocol: 'Lido',
    chain: 'ethereum',
    tokens: ['ETH'],
    tvl: 15000000000,
    tvlChange24h: 0.3,
    baseAPY: 3.8,
    rewardAPY: 0,
    totalAPY: 3.8,
    riskScore: 12,
    poolType: 'staking',
    ilRisk: 'None',
    farmUrl: 'https://lido.fi',
    isStablecoin: false,
  },
];
